### ISSUE TITLE
Choosing Xcode Version does not work wit curl

### ISSUE THREAD

**Issue by iv-mexx** [DynamicDust/xcode-plugin-updater#4]
I have multiple versions of Xcode installed (Release Version + Beta Version).
When trying to run your script via curl as in your Readme

```
curl -fsSL http://git.io/vvZMn | bash
```

the script just keeps printing `Please answer in range 0 - 1.` for ever, input from the user is impossible.

When cloning the repo and starting the script by hand

```
./xcode-plugin-updater.sh
```

everything works as expected.

**Comment by dominik-hadl** [comment]
@iv-mexx Ah, yes. You're right. 

I am quite busy right now, so I won't get to fixing it this week or next week. I will happily merge any pull requests though :)

**Comment by dominik-hadl** [comment]
@iv-mexx Just added a very messy, but working solution to this, as I had 5 minutes extra time. :)

**Comment by iv-mexx** [comment]
Yeah, works now. Thanks :+1:
