### ISSUE TITLE
Xcode 7.0 issue

### ISSUE THREAD

**Issue by EvgenyKarkan** [DynamicDust/xcode-plugin-updater#5]
It seems that script doesn't work with Xcode 7.

**Comment by dominik-hadl** [comment]
I've just tried it and it worked. Could you please be more specific about what seems not to work?

**Comment by EvgenyKarkan** [comment]
Ok, thanks, please take a look, maybe it will point you to issue reason.

Xcode 7.0 (7A220)
Mac OS X 10.10.5 (14F27)
Terminal 2.5.3 (343.7)

Here is the screenshot from terminal app with the result of command execution:
https://monosnap.com/file/56TPSFMIRxYNNCAp7uKlBBXSI4CAmL

I'm running an official Xcode, dowloaded from the App Store.

**Comment by EvgenyKarkan** [comment]
Update: 
With Xcode 7.0.1 (7A1001) script works as expected.

**Comment by dominik-hadl** [comment]
I've tested it with both versions now and I think this sometimes happens with Xcode installed from the App Store. I haven't identified the exact issue, but if you reinstall Xcode it should work as expected. I am closing this issue for now.

**Comment by EvgenyKarkan** [comment]
Ок.
